version: "3.8"

services:
  nginx-rtmp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1935:1935"
      - "8088:80"
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
